name: Pages
on:
 push:
   branches:
    - release
jobs:
 build:
   runs-on: ubuntu-latest
   steps:
   - uses: actions/setup-python@v2
   - uses: actions/checkout@master
     with:
       fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
   - name: Build and Commit
     run:  pip install sphinx-rtd-theme
     uses: sphinx-notes/pages@v2
     with:
        documentation_path: source
   - name: Push changes
     uses: ad-m/github-push-action@master
     with:
       github_token: ${{ secrets.GITHUB_TOKEN }}
       branch: gh-pages
